type Book {
    _id: ID
    title: String!
    author: User!
}

# BookInput is the data that is sent during the mutation
input BookInput {
    title: String!
    author: ID!
}

type QueriesHolder {
    getAllBooks: [Book]!
    getBookById(id: ID!): Book!
}

# data is an object with the BookInput format
type MutationsHolder {
    createBook(data: BookInput): Book!
    updateBook(id: ID!, data: BookInput): Book!
    deleteBook(id: ID!): Boolean
}

schema {
  query: QueriesHolder
  mutation: MutationsHolder
}