type User {
  _id: ID!
  firstName: String!
  lastName: String!
  fullName: String!
  email: String
  active: Boolean!
}

input UserInput {
  firstName: String!
  lastName: String!
  email: String
  active: Boolean
}

type QueriesHolder {
  users: [User!]!
  user(id: ID): User!
}

type MutationsHolder {
  createUser(data: UserInput!): User!
  updateUser(id: ID, data: UserInput!): User!
  deleteUser(id: ID!): Boolean
}

schema {
  query: QueriesHolder
  mutation: MutationsHolder
}
